name: auction_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tensorflow
  - keras
  - jupyter
  - missingno
